### ISSUE TITLE
Problem with generated API GlideApp

### ISSUE THREAD

**Issue by AndrewHossam** [firdausmaulan/GlideSlider#27]
I get this error when I add the library
I think it kind of conflict between my GlideApp and library GlideApp

> 2018-07-30 16:38:38.060 ? E/installd: Failed to delete /data/app/vmdl1721415789.tmp: No such file or directory
2018-07-30 16:38:39.038 ? E/Finsky: [2] com.google.android.finsky.wear.ad.a(3): onConnectionFailed: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
2018-07-30 16:38:40.360 ? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
2018-07-30 16:38:40.484 ? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
2018-07-30 16:38:42.027 ? E/ResourcesManager: failed to add asset path /data/app/com.example.myapp.debug-RQsxgyEeQth13RKqzpwItA==/base.apk
2018-07-30 16:38:42.027 ? E/ResourcesManager: failed to add asset path /data/app/com.example.myapp.debug-RQsxgyEeQth13RKqzpwItA==/base.apk
2018-07-30 16:38:42.027 ? E/ResourcesManager: failed to add asset path /data/app/com.example.myapp.debug-RQsxgyEeQth13RKqzpwItA==/base.apk
2018-07-30 16:38:42.528 com.example.myapp.debug E/RecyclerView: No adapter attached; skipping layout
2018-07-30 16:38:42.531 com.example.myapp.debug E/RecyclerView: No adapter attached; skipping layout
2018-07-30 16:38:43.334 com.example.myapp.debug E/RecyclerView: No adapter attached; skipping layout
2018-07-30 16:38:43.486 com.example.myapp.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapp.debug, PID: 11483
    java.lang.ClassCastException: com.glide.slider.library.svg.GlideRequests cannot be cast to com.example.myapp.utils.GlideRequests
        at com.example.myapp.utils.GlideApp.with(GlideApp.java:88)
        at com.example.myapp.home.coupons.CouponsAdapter.onBindViewHolder(CouponsAdapter.kt:37)
        at com.example.myapp.home.coupons.CouponsAdapter.onBindViewHolder(CouponsAdapter.kt:17)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1858)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1769)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:132)
        at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
        at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1361)
        at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:894)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
2018-07-30 16:38:43.487 com.example.myapp.debug E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2018-07-30 16:38:44.691 ? E/BeaconBle: Missing BluetoothAdapter
2018-07-30 16:38:44.732 ? E/BeaconBle: Scan couldn't start for Places
2018-07-30 16:38:53.527 ? E/memtrack: Couldn't load memtrack module
2018-07-30 16:39:08.124 ? E/memtrack: Couldn't load memtrack module
2018-07-30 16:39:08.145 ? E/memtrack: Couldn't load memtrack module
2018-07-30 16:39:17.021 ? E/memtrack: Couldn't load memtrack module
2018-07-30 16:39:17.037 ? E/memtrack: Couldn't load memtrack module
2018-07-30 16:39:30.266 ? E/memtrack: Couldn't load memtrack module
2018-07-30 16:39:30.289 ? E/memtrack: Couldn't load memtrack module

**Comment by firdausmaulan** [comment]
Already removed on new version. Thanks.
