### ISSUE TITLE
I am getting error with this libery.

### ISSUE THREAD

**Issue by shuvenduoffline** [firdausmaulan/GlideSlider#52]
Process: com.example.genesishospital, PID: 15301
    java.lang.NoSuchMethodError: No virtual method apply(Lcom/bumptech/glide/request/RequestOptions;)Lcom/bumptech/glide/RequestBuilder; in class Lcom/bumptech/glide/RequestBuilder; or its super classes (declaration of 'com.bumptech.glide.RequestBuilder' appears in /data/app/com.example.genesishospital-2/base.apk)
        at com.glide.slider.library.SliderTypes.BaseSliderView.bindEventAndShow(BaseSliderView.java:229)
        at com.glide.slider.library.SliderTypes.TextSliderView.getView(TextSliderView.java:25)
        at com.glide.slider.library.SliderAdapter.instantiateItem(SliderAdapter.java:82)
        at com.glide.slider.library.Tricks.InfinitePagerAdapter.instantiateItem(InfinitePagerAdapter.java:54)
        at com.glide.slider.library.Tricks.ViewPagerEx.addNewItem(ViewPagerEx.java:849)
        at com.glide.slider.library.Tricks.ViewPagerEx.populate(ViewPagerEx.java:999)
        at com.glide.slider.library.Tricks.ViewPagerEx.populate(ViewPagerEx.java:931)
        at com.glide.slider.library.Tricks.ViewPagerEx.onMeasure(ViewPagerEx.java:1454)
        at android.view.View.measure(View.java:20221)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
        at android.view.View.measure(View.java:20221)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
        at android.view.View.measure(View.java:20221)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.support.v7.widget.CardView.onMeasure(CardView.java:260)
        at android.view.View.measure(View.java:20221)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
        at android.view.View.measure(View.java:20221)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
        at android.view.View.measure(View.java:20221)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1638)
        at android.view.View.measure(View.java:20221)
        at android.support.constraint.ConstraintLayout.internalMeasureChildren(ConstraintLayout.java:1227)
        at android.support.constraint.ConstraintLayout.onMeasure(ConstraintLayout.java:1572)
        at android.view.View.measure(View.java:20221)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
        at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:733)
        at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:95)
        at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1556)
        at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:803)
        at android.view.View.measure(View.java:20221)
        at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
        at android.view.View.measure(View.java:20221)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:20221)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
        at android.view.View.measure(View.java:20221)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
    	at android.view.V

**Comment by firdausmaulan** [comment]
Seem like your app have more than 64K method count.
Have you implement multidex in your app?
https://developer.android.com/studio/build/multidex

**Comment by shuvenduoffline** [comment]
Nope! I can add and use any other repository. @firdausmaulan
