### ISSUE TITLE
IllegalArgumentException inc om.glide.slider.library.tricks.ViewPagerEx.onInterceptTouchEvent

### ISSUE THREAD

**Issue by Baresse** [firdausmaulan/GlideSlider#69]
Hi, 
I've some errors rising up in my app like this : 

 Fatal Exception: java.lang.IllegalArgumentException: invalid pointerIndex -1 for MotionEvent { action=MOVE, id[0]=1, x[0]=1409.11, y[0]=533.144, eventTime=633626302580000, downTime=633625813102000, deviceId=3, source=TOUCHSCREEN, displayId=0, eventId=726758915}
       at android.view.MotionEvent.nativeGetAxisValue(MotionEvent.java)
       at android.view.MotionEvent.getX(MotionEvent.java:2898)
       at androidx.core.view.MotionEventCompat.getX(MotionEventCompat.java:512)
       at com.glide.slider.library.tricks.ViewPagerEx.onInterceptTouchEvent(ViewPagerEx.java:1853)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2836)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3316)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2990)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:1116)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1971)
       at android.app.Activity.dispatchTouchEvent(Activity.java:4388)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:1074)
       at android.view.View.dispatchPointerEvent(View.java:15803)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:8153)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7877)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7213)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7270)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7236)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7434)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7244)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7491)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7217)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7270)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7236)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7244)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7217)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10788)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10676)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10632)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10926)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:285)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loopOnce(Looper.java:186)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

or like this :  

Fatal Exception: java.lang.IllegalArgumentException: pointerIndex out of range
       at android.view.MotionEvent.nativeGetAxisValue(MotionEvent.java)
       at android.view.MotionEvent.getX(MotionEvent.java:2608)
       at androidx.core.view.MotionEventCompat.getX(MotionEventCompat.java:512)
       at com.glide.slider.library.tricks.ViewPagerEx.onInterceptTouchEvent(ViewPagerEx.java:1853)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2753)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3222)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2904)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:697)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1879)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3487)
       at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:655)
       at android.view.View.dispatchPointerEvent(View.java:13732)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6128)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5906)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5355)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5408)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5374)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5533)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5382)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5590)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5355)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5408)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5374)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5382)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5355)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8417)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8350)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8303)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8532)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:198)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:187)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8491)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8559)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
       at android.view.Choreographer.doCallbacks(Choreographer.java:761)
       at android.view.Choreographer.doFrame(Choreographer.java:690)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

any hint on how can I solve this ? 

Thanks

**Comment by Baresse** [comment]
The following statement can return -1 : 

final int pointerIndex = MotionEventCompat.findPointerIndex(ev, activePointerId);

You shoud test the pointerIndex value not to be -1 before doing the following line : https://github.com/firdausmaulan/GlideSlider/blob/master/library/src/main/java/com/glide/slider/library/tricks/ViewPagerEx.java#L1853

is it possible to have a patch with this ? 

Best regards
